### ISSUE TITLE
Single Page Application authentication example

### ISSUE THREAD

**Issue by sedovalx** [t2v/play2-auth#121]
Hi!
I'm trying to figure out how to use play2-auth for the token based authentication with SPA-client. Can you help me with an example implementation? Or give some tips about steps for such authentication, please.
Thank you!

p.s.: I'm using Ember. But it can be any JavaScript client.

**Comment by gakuzzzz** [comment]
Hi,

What kind support do you needs?
[This URL](http://webcloud.info/blog/2014/04/07/emberjs-authentication-the-right-way-javascript-version/) seems helpful for Ember.js authentication.

play2-auth HTTP Basic Authentication sample is [here](https://github.com/t2v/play2-auth/tree/master/sample/app/controllers/basic)
You can wrote custom TokenAccessor using Header instead of Cookie.

Best,,
