### ISSUE TITLE
Issues if using unicode arrows (overloaded method value AsyncStack with alternatives)

### ISSUE THREAD

**Issue by jan0sch** [t2v/play2-auth#158]
Hi,

I just tried to compile a play project using play2-auth using unicode arrows (`→`) and the compiler bailed out like this:

````
overloaded method value AsyncStack with alternatives:
  (f: jp.t2v.lab.play2.stackc.RequestWithAttributes[play.api.mvc.AnyContent] 
    => scala.concurrent.Future[play.api.mvc.Result])play.api.mvc.Action[play.api.mvc.AnyContent] <and>
  (params: jp.t2v.lab.play2.stackc.Attribute[_]*)(f: jp.t2v.lab.play2.stackc.RequestWithAttributes[play.api.mvc.AnyContent] 
    => scala.concurrent.Future[play.api.mvc.Result])play
.api.mvc.Action[play.api.mvc.AnyContent] <and>
  [A](p: play.api.mvc.BodyParser[A], params: jp.t2v.lab.play2.stackc.Attribute[_]*)(f: jp.t2v.lab.play2.stackc.RequestWithAttributes[A] => scala.concurrent.Future[play.api.mvc.
Result])play.api.mvc.Action[A]
cannot be applied to ((AccountAdministration.this.AuthorityKey.type, models.AdminAuthority.type))
  def add = AsyncStack(AuthorityKey → AdminAuthority) {
            ^
````

Is there a way to make this work? Everything is fine if we stick to using `->` so I consider this a low priority issue. But it would be neat if it worked. :wink:

**Comment by gakuzzzz** [comment]
Hi,

It may be [stackable-controller](https://github.com/t2v/stackable-controller)'s issue.

The `->` method is defined [here](https://github.com/t2v/stackable-controller/blob/9b70ae5155025359bb98d4cdcf6a935411a2320f/core/src/main/scala/jp/t2v/lab/play2/stackc/StackableController.scala#L55) because of more type safety.

If you need `→`, you can send a PR to  [stackable-controller](https://github.com/t2v/stackable-controller) :)

**Comment by jan0sch** [comment]
Thanks, I'll try that. :-)

**Comment by jan0sch** [comment]
I made a PR for the stackable-controller: https://github.com/t2v/stackable-controller/pull/24

**Comment by gakuzzzz** [comment]
thanks! play2-auth 0.14.2 has been released that contains it.
